# Generated by Django 4.2.1 on 2023-07-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('title_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
