# Generated by Django 4.2.1 on 2023-07-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_context_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='context_image',
        ),
    ]
