# Generated by Django 4.2.1 on 2023-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_delete_mymodel_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='font_name_image',
            field=models.CharField(default='Default Font', max_length=100),
        ),
    ]
